site_name: My Docs

nav:
  - Principal: index.md
  - Acerca de: about.md
  - Practicas: practicas.md
  - Pruebas: deprueba.md

theme:
  name: material
  language: es
  palette:
    primary: lime    
  font:
    text: roboto


